### PR TITLE
Make input label's background transparent

### PR DESCRIPTION
**Pull request by jagodarybacka**
Resolves https://github.com/tahowallet/extension/issues/3269

### What
Try to make transparent background that will ignore input border by using blur effect.

WIP - Animation is not perfect as blur catches border color during the transition.

image

https://user-images.githubusercontent.com/20949277/233369054-187cae70-a046-43ce-88d1-dbf40176278b.mov

Latest build: [extension-builds-3291](https://github.com/tahowallet/extension/suites/12368619258/artifacts/656954723) (as of Thu, 20 Apr 2023 12:47:03 GMT).

### CODE REVIEW

**Comment by Shadowfiend** [comment]
So, this is imperfect but I feel like it's still workable as-is. Unless you're morally opposed @jagodarybacka I would love to let Vlad look at it and potentially land it as-is?

**Comment by jagodarybacka** [comment]
Well Vlad can take a look but to me it is not ready yet, but I'll let you decide if it looks better or worse than with the background.

**Comment by VladUXUI** [comment]
but judging by the video, i'm not fan of the blinking orange on transition
i would say close the pr and try to improve another time.

But this is an awesome step in the right direction :D, thank you @jagodarybacka

**Comment by jagodarybacka** [comment]
Yeah I believe it was a right direction but more polishing will be needed, let's drop it for now

**Comment by Shadowfiend** [comment]
Thanks folks!

**Pull request closed without merging**
