### PR TITLE
Release 0.37.0

### PR DESCRIPTION
**Pull request by Shadowfiend**
## What's Changed
* Ledger Respect: Attempt #2 at fixing Ledger connection issues by @Shadowfiend in https://github.com/tahowallet/extension/pull/3432
* v0.36.0 by @kkosiorowska in https://github.com/tahowallet/extension/pull/3427
* Fix UI crash when gas fee data is unavailable by @hyphenized in https://github.com/tahowallet/extension/pull/3434
* v0.36.1 by @jagodarybacka in https://github.com/tahowallet/extension/pull/3436
* Fix duplicate base assets being stored in redux asset cache by @hyphenized in https://github.com/tahowallet/extension/pull/3431
* Facilitated Connections: Add updated dApp Connections flag, clean up a bunch of other feature flags by @Shadowfiend in https://github.com/tahowallet/extension/pull/3446
* Unsigned Integers: Remove everything in `ui/components/SignTransaction` by @Shadowfiend in https://github.com/tahowallet/extension/pull/3404
* Drop the `AddressOnNetwork` parameter for token import by @kkosiorowska in https://github.com/tahowallet/extension/pull/3426
* Dial-up Connection: Add placeholders for new dApp Connections flow by @Shadowfiend in https://github.com/tahowallet/extension/pull/3447
* Fix issue for assets list for swapping/sending  by @kkosiorowska in https://github.com/tahowallet/extension/pull/3452
* NFTs flag cleanup by @jagodarybacka in https://github.com/tahowallet/extension/pull/3421
* Use the multisig community address for a specific chain by @kkosiorowska in https://github.com/tahowallet/extension/pull/3443
* Fixes for the verification of tokens by @kkosiorowska in https://github.com/tahowallet/extension/pull/3454
* Open the transaction details in new tab when activity is not available by @kkosiorowska in https://github.com/tahowallet/extension/pull/3457
* Verified/Unverified tokens  - QA Build  by @kkosiorowska in https://github.com/tahowallet/extension/pull/3424

Latest build: [extension-builds-3461](https://github.com/tahowallet/extension/suites/13474523526/artifacts/739579701) (as of Thu, 08 Jun 2023 19:30:13 GMT).

### CODE REVIEW

**Review by SJQuality — APPROVED** [review]
QA Approved

**Comment by beemeeupnow** [comment]
I really like the swap page updates!
It would be nice if state was kept on the swap page. (for example, if you Reject the transaction you are taken back to the swap page but all controls are reset)

For unverified assets: 
* If the user for some reason enables the setting to show them, then later decides to disable it again in the settings page, it seems that they are blocked from adding any of the unverified assets by contract address using "Add custom asset" in the wallet view. (the UI shows "Asset already exists, you will see it once your balance is over 0", and you are unable to proceed)
* If the user tried to use "Add custom asset" with the unverified assets setting enabled and the contract matches an existing unverified asset, I feel it would make sense to allow adding it or take them to the verification page for the asset. (same UI result as above currently)
* If you hide a verified/unverified asset then try to add it with "Add custom asset" it also blocks with the same message

I think that the UI would feel more uniform if assets that are "built-in"/came from lists had an indicator in the same area as the "Verified by you"/"Asset not verified" (in the view when you click on an asset from the main wallet page)

**Comment by Shadowfiend** [comment]
This is great feedback and some awesome finds @beemeeupnow ! I think all of it is non blocking but we're going to try to look at it next week for sure 🙇

**Comment by mhluongo** [comment]
I like that that approach let's us generalize verification as just another token list... then one day people could export their personal token lists... 👀

**Comment by VladUXUI** [comment]
Awesome feedback @beemeeupnow !
Agree on most of the above, especially the fact that "add asset" should supersede unverified assets and should not block users from adding it.

**Pull request merged**
