### PR TITLE
Add support for BIP39 passphrase

### PR DESCRIPTION
**Pull request by beemeeupnow**
Allow advanced usage of [BIP39](https://en.bitcoin.it/wiki/BIP_0039#From_mnemonic_to_seed) passphrase when importing an existing wallet from seed phrase

Relies on tallycash/hd-keyring#8

### CODE REVIEW

**Comment by cairomassimo** [comment]
I see the UI is still missing in this PR (I'm assuming that's why it's still in draft). @beemeeupnow you could add a quick-and-dirty UI for this, protected by a feature flag. This way we have a much higher of merging this (on one hand the code could be tested immediately, on the other hand we don't have to wait for a proper UI design). @mhluongo what do you think about it?

**Comment by beemeeupnow** [comment]
Thank you for looking at this @cairomassimo 

Yes, I need to add some simple interface next.

I was waiting on tallycash/hd-keyring#8 to be reviewed and merged first to further simplify testing of this PR for others. (it can be merged before this one without breakage)

**Comment by beemeeupnow** [comment]
@cairomassimo I added a feature-flagged text box for the passphrase (env var HIDE_IMPORT_PASSPHRASE)

tallycash/hd-keyring#8 needs to be merged and a new package release before I move this one from draft, as I'll need to bump the expected hd-keyring version

**Comment by beemeeupnow** [comment]
As discussed in [tallycash/hd-keyring#8](https://github.com/tallycash/hd-keyring/pull/8#discussion_r831730805), once tallycash/extension#1165 is complete I will update this PR so that keyrings with passphrases are handled in such a way that we don't store the passphrase.

That PR will allow adding a special UI flow where we can ask for the passphrase when we are signing and enable me to better implement the feature.

**Comment by beemeeupnow** [comment]
looping back to this now that tallycash/extension#1165 has been merged for a bit
 
My goal is to have it behave like an imported wallet in that you don't have to enter the mnemonic each time you use it but each time the key material is needed it will require entering the passphrase.

**Comment by Shadowfiend** [comment]
If you start building on the work in #1697, the final implementation of RFB 2 should be substantially similar. The `SignerKeyringFrame` is going to be the place to hook in.

**Comment by Shadowfiend** [comment]
Closing this for now as we've drifted from the feature flag approach (`SHOW_` vs `HIDE_`), we have to hold for a while on keyring changes until we land an audit for account backup (#3252), onboarding has been refactored a bit, and finally we're looking at a different approach to handling signing.

If and when you want to pick this back up @beemeeupnow , feel free to reopen the PR or open a new one built against the latest state of `main`. I do still think this is worthy work!

**Pull request closed without merging**
