### PR TITLE
DAppstrosities: Fix a few observed dApp connection issues

### LINKED ISSUE #3578: Uniswap requiring a page refresh after default on/off
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to Uniswap through MetaMask, while Taho was set to default

### What did not work?

When installed side by side, and Taho is set to default, Taho will come up when a user selects MetaMask. The user can then:

1. Connect with Taho
2. Reject the connection, open Taho and set Taho as default to Off
3. Switch Taho as default to Off in the connection pop-over

**Desired behavior:** Ideally, when a user selects 2 or 3, this would take effect immediately: When a user would select MetaMask again, MetaMask would come up. The user wouldn't need to refresh the dApp.

**Current behavior- scenario 2**: After rejecting, the pop-over closes. The user can then select MetaMask again, but when doing so Uniswap will throw an error - see recording.

A dApp refresh is needed in order to be able to connect with MetaMask.

**Current behavior- scenario 3**: After switching to default off, Uniswap directly throws an error - see recording.

A dApp refresh is needed in order to be able to connect with MetaMask.

https://github.com/tahowallet/extension/assets/71384922/2de35a63-8e56-45c2-b728-a262ac198efb

I don't know if this is helpful, but the background page console says

Screen Shot 2023-07-28 at 19 49 06

 

### Version

v0.43.3

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Shadowfiend**
- Uniswap should now update default wallet without reloads (closes #3578).
- Stargate should correctly handle transfers when the chain needs to be changed behind the scenes.
- Generally sites that may interact with event handlers before Taho's default status is read should no longer have issues.

## Testing

- [x] Go to Uniswap with Taho as default and try to connect with MetaMask. In the popup, switch away from Taho as default. MetaMask should connect normally.
- [x] Go to Uniswap with Taho as default and try to connect with MetaMask. In the popup, reject. Switch Taho as default off in the popover. Try to connect with MetaMask again. MetaMask should connect normally.
- [x] Go to Uniswap with Taho as not-default. Switch Taho as default on in the popover. Try to connect with MetaMask. Taho should connect normally.
- [x] Go to Stargate with Taho as default. Connect. Set up a swap from a *different* network than the one you connected on (I typically connect on Ethereum mainnet, then set a swap from Arbitrum ETH to mainnet ETH). Try to submit the transaction. You should get a transaction confirmation.

Latest build: [extension-builds-3593](https://github.com/tahowallet/extension/suites/14936639887/artifacts/851517366) (as of Wed, 09 Aug 2023 02:29:24 GMT).

### CODE REVIEW

**Comment by andreachapman** [comment]
Hey @Shadowfiend, I have a couple of things to clarify.

**For the Stargate issue:** I took a video of what I was seeing on the current prod version and what I see now. I think the error is resolved but I just wanted to confirm that the error I saw is what y'all were also seeing and that there wasn't something else I was missing in reproducing. So this is the first video of production: 

https://github.com/tahowallet/extension/assets/135037801/0cdef63d-bbec-4ce8-8ee4-c910d1a407f1

And here's the video from the version in this PR: 

https://github.com/tahowallet/extension/assets/135037801/866ed79f-e614-45b3-9be4-8827c47a977b

You don't see the completion of the transaction because it took a few minutes but you see it get past the point where it failed in the previous extension version. And I confirmed it did complete successfully. 

On thing I want to point out that I noticed here is what you see when connecting the wallet. In the current prod version, you can see in the video that when you connect the wallet (Taho is default), you see the label "Taho" and the MM icon. And then in this PR version of the extension, Taho is still the default wallet but you see the label "MetaMask" with the MM icon. So was this intended and correct or should it have not changed?

**RE: the Uniswap issue:** Here's a video I took of the first test listed "Go to Uniswap with Taho as default and try to connect with MetaMask. In the popup, switch away from Taho as default. MetaMask should connect normally."

https://github.com/tahowallet/extension/assets/135037801/798f553d-9837-4cba-862e-5812e15cc617

I'm not seeing MM connect normally after switching from Taho as default. I'm seeing infinite spinning on the MM connect button. So that doesn't seem like what we intended, though the error is gone. I still end up having to reload the page in order to connect with MM in this scenario.

**Comment by Shadowfiend** [comment]
I'll dig with both Uniswap things.

> The last line says "MetaMask should connect normally" but if we've switched to Taho as default, do we mean that clicking the MM option should connect the site to Taho normally? Or am I misunderstanding that?

The first line says “Go to Uniswap with Taho as **not**-default”. 100% not the best or most scannable way to say that haha. I really mean switch the Taho default toggle to MetaMask, or turn off Taho as default.

**Comment by Shadowfiend** [comment]
Oiiii you're right. Let me revisit this afternoon and double-check what I meant hehe.

**Comment by Shadowfiend** [comment]
Ok correct, goal was to check that Taho connects correctly in that scenario. Updated the PR description accordingly.

Re: the errors you were seeing, I'm having trouble reproducing. Maybe we should do some sync time to see if I can see it on your machine.

**Comment by andreachapman** [comment]
I tried everything again this morning and don't see the issues I was seeing yesterday. I think the order of operations I did yesterday was causing some strange issues. So today, I removed the connected sites from the current prod version of the extension _before_ I disabled it in the extension manager. Then, I completely removed this version and then added it anew without any other version enabled to possibly conflict. Now when running through the tests, it's all working according to the expected results. Maybe yesterday I messed up because I first had to reproduce in prod but then when I disabled that version, something was obviously still connected and causing conflicts. Sorry for the extra work here!

Go to Uniswap with Taho as default and try to connect with MetaMask. In the popup, switch away from Taho as default. MetaMask should connect normally. 

https://github.com/tahowallet/extension/assets/135037801/2cbc8377-5240-425c-81e9-c7d83916c2e9
 
Go to Uniswap with Taho as default and try to connect with MetaMask. In the popup, reject. Switch Taho as default off in the popover. Try to connect with MetaMask again. MetaMask should connect normally. 

https://github.com/tahowallet/extension/assets/135037801/78da8832-8b11-4a56-a2f9-1404b412163f
 
Go to Uniswap with Taho as not-default. Switch Taho as default on in the popover. Try to connect with MetaMask. Taho should connect normally. 

https://github.com/tahowallet/extension/assets/135037801/b9401cfc-a337-4815-9a29-73fb9e1b7b94

And Stargate transfers were working yesterday too. So I think this is all good to go.

**Comment by Shadowfiend** [comment]
All right, appreciate it!

**Review by hyphenized — CHANGES_REQUESTED** [review]
Attempting to connect to stargate.finance yields an error




Inspecting the wrapped provider shows this for me

**Comment by Shadowfiend** [comment]
This fellow should be fixed.

**Review by hyphenized — APPROVED** [review]
Works well now!

**Pull request merged**
