### PR TITLE
Custom Networks - QA Build

### PR DESCRIPTION
**Pull request by hyphenized**
### Checklist
- Head to chainlist.org, connect your wallet
- Adding a network
	- [x] Confirmation screen displays after clicking on "Add network"
	- [x] Confirmation screen displays new network data:
		- Name, Chain ID, Base asset symbol, RPC and block explorer URLs
	- [x] Network displays in the network switcher
	- [x] Switching to the new network works
	- [x] Wallet loads and display base asset balance
	- [x] Network appears in custom networks settings page
- Sending transactions
	- [x] Send network base asset
	- [x] Receive network base asset
	- [x] Balance updates after sending/receiving
- Removing a network
	- [x] Wallet automatically switches the network back to Ethereum
	- [x] Network no longer appears in the network switcher
 	- [x] Network no longer appears in custom networks settings page
- DeFi Things
	- [x] DEX Swap
	- [x] Providing Liquidity

Latest build: [extension-builds-3147](https://github.com/tahowallet/extension/suites/12516630797/artifacts/669572221) (as of Thu, 27 Apr 2023 22:12:16 GMT).

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
Compiling a list of issues here as I QA:

- Custom Networks back button spits you to settings menu rather than back where you came from

https://user-images.githubusercontent.com/94649004/224985211-0d75dde8-851e-497c-ad6f-17b1d74f2a3f.mov

- Social buttons & version number are cut off on Settings page

image

- Add Custom Advanced RPC button does not actually do anything (nor should it - but should probably be hidden)
image

- Trying to connect wallet to Chainlist  fails and spits out `{code: 4100, message: 'The requested method and/or account has not been authorized by the user.'}`

**Review by kkosiorowska — COMMENTED** [review]
I've noticed strange behavior. I added a new network then deleted it and tried to add another ones. After that I am not able to add any new network. 

https://user-images.githubusercontent.com/23117945/225895291-5bd1c4d5-6f02-4431-93ed-da2ab25b9246.mov

**Comment by Naxsun** [comment]
This could be a decision as well, hence not ticketed yet. I added a custom token on Fantom.

https://ftmscan.com/token/0x841fad6eae12c286d1fd18d1d525dffa75c7effe?a=0x0581470a8b62bd35dbf121a6329d43e7edd20fc7

Although I added it myself, it makes it a hidden asset. Since I added it myself I would not expect it to be a hidden asset.

Screen Shot 2023-04-19 at 09 36 02


Screen Shot 2023-04-19 at 09 36 13

It does not have a price (I don't know how hour <$2 feature works for assets without prices loading, but this setting is disabled anyway).

**Comment by VladUXUI** [comment]
Just finished testing. There are some ux/ui bugs i would like to fix before we ship. Yes, i understand that this means we aren't going to ship this week. Will ticket shortly

**Comment by VladUXUI** [comment]
Good points @Naxsun 
> Although I added it myself, it makes it a hidden asset. Since I added it myself I would not expect it to be a hidden asset.
This actually added it as a untrusted asset, and that shouldn't happen. But if your balance is under <$2 it will indeed show up in the hidden section. And you won't see it at all if you have 0.000 balance.
 
 
Swap buttons should only be disabled for untrusted assets, not for assets with dust. Ticketed both bellow

 
https://github.com/tahowallet/extension/issues/3295

**Review by 0xDaedalus — APPROVED** [review]

**Pull request merged**
