### PR TITLE
Onboarding Revamp QA

### PR DESCRIPTION
**Pull request by hyphenized**
## Onboarding Revamp QA

Design: 
[Tabbed Onboarding](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=13399%3A257622)
[Additional accounts](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=7802%3A202104)

### Checklist
- Fresh install
  - [x] Extension opens onboarding tab with "Lets get you setup screen"
  - [x] Clicking the extension in the toolbar opens onboarding
  - [x] Attempting to connect to a dApp opens onboarding
  - Onboard existing account
    - [x] Import seed phrase
    - [x] Connect to ledger
    - [x] Add preview/read-only account
  - Onboard new seed
    - [x] Seed verification works
    - [x] Back button resets generated seed
  - [x] Completing onboarding takes you to the Welcome to Taho / Wallet shortcut screen
  - [ ] Content in the left side panel changes depending on the current user path (see design)
  - [x] Actions in the left side panel work

- Active install
  - [x] Clicking Add Wallet through the popup opens the onboarding tab
  - [x] Attempting to add an account with the wallet locked opens the unlock screen
  - [x] No left side panel
  - [x] Completing onboarding takes you to "Account added to Taho" / Wallet shortcut screen

- [x] Confirm seed phrase is not leaked to Chrome session data for the onboarding flow or the add wallet flow. (Signed off by @Shadowfiend.)

Latest build: [extension-builds-3097](https://github.com/tahowallet/extension/suites/11837487093/artifacts/618448870) (as of Mon, 27 Mar 2023 16:17:37 GMT).

### CODE REVIEW

**Comment by kkosiorowska** [comment]
>  Attempting to connect to a dApp opens onboarding

Tested with sushi, uniswap, curve cowswap.

**Comment by kkosiorowska** [comment]
I tested a few points. Everything works well 🚀 A few minor comments on the differences in design. These are very minor things that I noticed while going through the test steps. However, they do not block this PR. 

- Missing copy option for read-only account
Screenshot 2023-03-15 at 09 22 18

Screenshot 2023-03-15 at 09 22 10

- Read-only account tab name

Screenshot 2023-03-15 at 09 21 30

Screenshot 2023-03-15 at 09 21 25

- Text for Ledger

Screenshot 2023-03-15 at 09 30 58

Screenshot 2023-03-15 at 09 31 31

**Review by jagodarybacka — COMMENTED** [review]
Two issues for me:
- non-blocking - keyboard shortcut is not working for me (can someone else try? maybe I messed it up with other software shortcuts)
- kinda blocking IMO - on the NFTs page add account button is not using tabbed onboarding
image

**Comment by kkosiorowska** [comment]
> non-blocking - keyboard shortcut is not working for me (can someone else try? maybe I messed it up with other software shortcuts)

In my case, the keyboard shortcut works on the mac. 

> * kinda blocking IMO - on the NFTs page add account button is not using tabbed onboarding
>   image

The same for abilities page.

Screenshot 2023-03-15 at 12 41 25

**Review by Shadowfiend — APPROVED** [review]
Issue with NFTs and abilities page add account links not entering tabbed onboarding have been fixed, sounds like everything else here isn't a blocker. Let's rock and roll!

**Pull request merged**
