### PR TITLE
Add Trezor Support

### PR DESCRIPTION
**Pull request by PabloCastellano**
Hello!

Based on the Ledger implementation I am here drafting the Trezor implementation.

This is not working because the trezor popup is closed. My trezor is connected but I don't get prompted to enter my PIN. Any ideas?

https://user-images.githubusercontent.com/73274/159167441-1440aba2-2452-49a4-862f-5e46397a70c4.mp4

## Test it

```
git remote add pablocastellano https://github.com/PabloCastellano/extension.git
git fetch pablocastellano
git checkout -b pablocastellano/trezor-support-final
```

Also add `HIDE_IMPORT_TREZOR=false` to your `.env`.

## Open questions

* Should we allow the popup from trezor somehow in manifest.json? (I have no previous experience with extensions development so I'm not sure if it makes sense)
* Should we initialize `TrezorConnect` in TrezorService instead?
* Where is the correct place to place `<script src="https://connect.trezor.io/8/trezor-connect.js"></script>`?

## TODO

* [ ] Trezor One working
* [ ] Finish Trezor UI (now borrowing Ledger UI)

## Logs

console logs:

```
trezor: manifest
DevTools failed to load source map: Could not load content for chrome-extension://aldgjcfonekifbpplgdgnblkoidoolid/provider-bridge.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
provider-bridge.js:258  content: background > inpage: {"id":"tallyHo","result":{"method":"tally_getConfig","defaultWallet":true}}
DevTools failed to load source map: Could not load content for chrome-extension://aldgjcfonekifbpplgdgnblkoidoolid/window-provider.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

### CODE REVIEW

**Comment by fernya** [comment]
Hey @PabloCastellano, my 2 cents are:

> Should we allow the popup from trezor somehow in manifest.json? (I have no previous experience with extensions development so I'm not sure if it makes sense)

I think if that would be forbidden to show right now then you wouldn't have it on your video showing up intermittently.
It would be good to somehow [block the closing event](https://stackoverflow.com/questions/11136010/how-do-i-prevent-chrome-developer-tools-from-closing-when-the-current-browser-wi) of that window and check the console and see if that has anything useful for us!


> Should we initialize TrezorConnect in TrezorService instead?

That would be appropriate but first its good enough to see something during onboarding flow! :)

> Where is the correct place to place <script src="https://connect.trezor.io/8/trezor-connect.js"></script>?

For testing purposes you might experiment with hardwiring it into `ui/public/tab.html` but I don't think that its the culprit right now!

**Comment by PabloCastellano** [comment]
@fernya I have tried blocking the closing event but I haven't got anything useful. Also did some changes in the manifest.json file but nothing relevant, probably because I don't have so much experience with extensions development.

**Comment by greg-nagy** [comment]
@PabloCastellano I would love to see this land in the extension 💪

But at the moment we are pretty much in churn mode for release and trezor is not on the requirement list for v1. 
Is it ok with you, if we circle back to this integration after v1 release? 

I will gladly spend some time on debugging this issue :) 
Not sure how the implementation works for trezor, but could it be loaded in an iframe?

**Comment by Shadowfiend** [comment]
@PabloCastellano are you still interested in implementing Trezor support? Asking as we look to clean up stale PRs and figure out what's next.

**Comment by mhluongo** [comment]
Closing this as stale. If you're interested in picking this back up let us know @PabloCastellano!

**Pull request closed without merging**
