### PR TITLE
Update the spinner variant styles

### PR DESCRIPTION
**Pull request by kkosiorowska**
This PR fixes the issue with spinner variant styles.

**UI**
- `dark-green` variant
Screenshot 2023-03-08 at 11 23 19

- `hunter-green` variant
Screenshot 2023-03-08 at 10 53 58

- `transparent` variant
Screenshot 2023-03-08 at 10 54 54

Latest build: [extension-builds-3127](https://github.com/tahowallet/extension/suites/11479525702/artifacts/592752882) (as of Fri, 10 Mar 2023 12:56:39 GMT).

### CODE REVIEW

**Comment by VladUXUI** [comment]
This is perfect!

**Review by jagodarybacka — COMMENTED** [review]
This spinner on asset item (Wallet page) was green before - do we want to change it?
image

**Comment by kkosiorowska** [comment]
> This spinner on asset item (Wallet page) was green before - do we want to change it? 

I have set the default to the previous color `--green-80` variant so that there are no visibility issues. In addition, previously there was an issue in the name of the color. Change from `--trophygold` to `--trophy-gold`.

**Review by jagodarybacka — APPROVED** [review]
lgtm 🚀

**Pull request merged**
