### PR TITLE
Fixes for verified/unverified assets

### PR DESCRIPTION
**Pull request by kkosiorowska**
## What

- Update the editing flow of the asset between the db and the UI. Check out this [post](https://github.com/tahowallet/extension/pull/3394#pullrequestreview-1444570845).
- The list of unverified assets should close automatically only after switching accounts.
- Fix the issue with the missing "sliding up/down" animation
- Minor improvements

## UI

https://github.com/tahowallet/extension/assets/23117945/bf8b09b1-7feb-49e1-a3a0-0a7c50fa0cc4

## To Test
- [x] Check that the list is not automatically closed after the asset verification action.
- [x]  Verify the asset and add them to the regular list. The status of db and redux should be updated.

## Testing Env

```
SUPPORT_UNVERIFIED_ASSET=true
```

Latest build: [extension-builds-3410](https://github.com/tahowallet/extension/suites/13217763173/artifacts/719968230) (as of Mon, 29 May 2023 12:37:13 GMT).

### CODE REVIEW

**Review by jagodarybacka — COMMENTED** [review]
Problems I've found:

- "Asset automatically imported" slideup is missing "sliding up/down" animation
- I got pretty bad lag once when I've clicked "Add to asset list" on the first asset - can't reproduce that, but something to keep an eye on 😉

**Comment by kkosiorowska** [comment]
> "Asset automatically imported" slideup is missing "sliding up/down" animation

Fixed.

> I got pretty bad lag once when I've clicked "Add to asset list" on the first asset - can't reproduce that, but something to keep an eye on 😉

hmm it's strange. I will try to reproduce and fix in future PR If I find something.

**Review by jagodarybacka — CHANGES_REQUESTED** [review]
Looks good, lets reuse that one function and we are probably ready to go ;) 

Non blocking but should be improved in the future:
- user should be at least able to copy tx hash or should be able to see that transaction on the scan website
image
- add a browser title tooltip to the text with ellipsis 
image
- that whitespace looks weird to me 
image

**Comment by kkosiorowska** [comment]
> user should be at least able to copy tx hash or should be able to see that transaction on the scan website

This issue is resolved in this  https://github.com/tahowallet/extension/pull/3416.

> add a browser title tooltip to the text with ellipsis

Fixed.
> that whitespace looks weird to me

 @VladUXUI Do you have any suggestions for it?

**Review by jagodarybacka — APPROVED** [review]
LGTM

**Comment by VladUXUI** [comment]
>@VladUXUI Do you have any suggestions for it?

I do not, i think Antonio brought it up as well, but i don't have a decent fix for this atm.

But not a blocker

**Pull request merged**
