### PR TITLE
Add Alchemy endpoint for Arbitrum Sepolia

### PR DESCRIPTION
**Pull request by jagodarybacka**
### What

As Alchemy started to support Arbitrum Sepolia we can switch the wallet to use Alchemy endpoint by default.

Issues:
- ethers providers doesn't know about Arbitrum Sepolia network, workaround was added (same as for eth sepolia network)
- seems like there is a problem with using `external` flag for `alchemy_getAssetTransfers` on Arb Sepolia, it is responding with server error that these are not supported on a given chain [despite docs claiming otherwise](https://docs.alchemy.com/reference/alchemy-getassettransfers)
- `alchemy_getTokenBalances` is failing often with server error (timeout) - seems like it is a problem on Alchemy side 

These are not totally blocking because most of the time requests are working fine and we have backup providers as well but I would rather talk to Alchemy support about these problems first, before merging this PR.

### Testing steps

- [ ] reinstall extension/reload background script
- [ ] open the background console
- [ ] add some accounts, use Arbitrum sepolia network
- [ ] make sure requests are going through the Alchemy's Arbitrum Sepolia endpoint

Latest build: [extension-builds-3665](https://github.com/tahowallet/extension/suites/18347933259/artifacts/1061913309) (as of Mon, 20 Nov 2023 16:33:19 GMT).

### CODE REVIEW

**Comment by jagodarybacka** [comment]
Moving to draft until Alchemy issues will be resolved

**Comment by jagodarybacka** [comment]
Actually tested again and it is now working as expected. Ready for review.

**Review by ioay — APPROVED** [review]

**Comment by ioay** [comment]
Please update the branch with the main and check playwright tests, because there's a timeout issue.

**Comment by jagodarybacka** [comment]
@ioay e2e are failing everywhere - https://github.com/tahowallet/extension/pull/3651 should fix it.

Feel free to click Update branch if there are no conflicts.

**Pull request merged**
