### PR TITLE
Ledger Respect: Attempt #2 at fixing Ledger connection issues

### LINKED ISSUE #3419: Blank page on disconnected ledger
Introduced in v0.34.0

If the Ledger goes to sleep/screensaver and a dapp requests a signature, there is an error and the wallet UI shows up blank.

Ledger_sleeping

v0.32.0 (working) for reference:
v0 32 0_check_Ledger

v0.34.0 (broken) and higher:
v0 34 0_blank

_Originally posted by @beemeeupnow in https://github.com/tahowallet/extension/issues/3407#issuecomment-1564524469_

### PR DESCRIPTION
**Pull request by Shadowfiend**
Maybe fixes #3419.

Compare against #3420, and let's land the one that seems to work + be most correct while we debug further.

Latest build: [extension-builds-3432](https://github.com/tahowallet/extension/suites/13347808183/artifacts/729885779) (as of Sat, 03 Jun 2023 12:24:37 GMT).

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Testing some more, this looks like it does in fact do the trick:

- `onConnection` does not block on a connected Ledger that was unlocked then auto-locked.
- Refreshing the Ledger connection is working correctly.
- Errors are logged correctly that were previously being thrown and breaking the loading of the signing UI.

**Review by kkosiorowska — COMMENTED** [review]
I have tested the solution and it seems to be working well. I have additionally tested the bug from https://github.com/tahowallet/extension/pull/3380 and it does not cause regression either.

**Review by jagodarybacka — APPROVED** [review]
I like this solution more as this is simpler

Non blocking issues I see:

- [deriveAddressOnLedger](https://github.com/tahowallet/extension/blob/38e67acfe9aa1295a6df92529c857a815f594883/background/services/ledger/index.ts#L116-L124) which is throwing error while Ledger is asleep is not guarded with a try-catch here and this method is used in other places as well.

- I see the lag from loading the signing screen is a little bit longer here when Ledger is ready for signing (`Promise.all` fault I guess) so would be nice to make sure the skeleton loader is visible instead of just a blank screen.

https://github.com/tahowallet/extension/assets/20949277/840d96aa-628f-4cdb-a74c-1e1fbb331a07

**Comment by Shadowfiend** [comment]
> I see the lag from loading the signing screen is a little bit longer here when Ledger is ready for signing (Promise.all fault I guess) so would be nice to make sure the skeleton loader is visible instead of just a blank screen.

Yeah wondering if we can move to `allSettled` or something there as well. Def worth poking at.

**Pull request merged**
