### PR TITLE
Show full network name on network delete

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Closes https://github.com/tahowallet/extension/issues/3323

image

Latest build: [extension-builds-3353](https://github.com/tahowallet/extension/suites/12825684976/artifacts/690736971) (as of Thu, 11 May 2023 10:37:30 GMT).

### CODE REVIEW

**Review by kkosiorowska — CHANGES_REQUESTED** [review]
The text jumps to the next line for long names and truncates the buttons.

Screenshot 2023-05-02 at 10 10 06

**Review by jagodarybacka — COMMENTED** [review]
So what's a current requirement? Seems like now it is not showing full name and we just made the name wider
image

**Comment by jagodarybacka** [comment]
Fixed:
imageimage

**Review by kkosiorowska — APPROVED** [review]
LGTM :white_check_mark:

**Pull request merged**
