### PR TITLE
Pull asset prices from on chain oracles

### PR DESCRIPTION
**Pull request by 0xDaedalus**
This PR makes use of the [1inch Spot Price Aggregator](https://docs.1inch.io/docs/spot-price-aggregator/introduction/) contracts to allow the extension to fetch asset prices without reliance on Coingecko APIs.  This should alleviate some of the issues users are reporting around prices not showing up in the extension - and give us an alternative path to querying asset prices via coingecko should the coingecko api ever become private.

### To Test
- [x] Install a fresh copy of the extension (do NOT import a wallet yet)
- [x] Block requests to `api.coingecko.com` via devtools
- [x] Import a wallet
- [x] You should see asset prices!
- [x] Switch to polygon / optimism / arbitrum - you should see asset prices!
- [x] Unblock `api.coingecko.com`, refresh the extension until you start getting `429`'s from coingecko - you should see extension fallback to fetching prices via oracle (you can add logs for this, or observe `eth_call` requests being sent to the respective network's json rpc endpoint).

https://user-images.githubusercontent.com/94649004/230989266-29f695ea-1300-41d4-93a0-d7bd13212ab6.mov

Latest build: [extension-builds-3264](https://github.com/tahowallet/extension/suites/13492591655/artifacts/741032674) (as of Fri, 09 Jun 2023 13:33:14 GMT).

### CODE REVIEW

**Comment by 0xDaedalus** [comment]
Hmmmn unfortunate - I took out some unnecessary `await`ing of promises - can you give it another shot?

**Comment by jagodarybacka** [comment]
I can't see a difference from yesterday, it's still lagging pretty badly especially if I add more than one account while the others are still loading prices/assets. I also noticed that after a while (when prices were loaded) it was lagging my whole Chrome until I uninstalled the extension 😭

**Comment by jagodarybacka** [comment]
I can no longer reproduce that performance problem, even adding 10 accounts is working fine with blocked coingecko. 

@kkosiorowska can I ask you to test this PR manually as well? With coingecko blocked and unblocked. Previously when I added 5-6 accounts extension UI was very laggy, the animations were not smooth and everything was reacting with a delay.

**Review by jagodarybacka — APPROVED** [review]
Seems ok. Let's give it a try 🚀

**Pull request merged**
